id: fhir.ca-bc.provider
canonical: http://hlth.gov.bc.ca/fhir/provider
name: BCProviderRegistry
title: BC Provider Location Registry FHIR Implementation Guide
description: FHIR Implementation Guide for BC MOH Provider Registry
status: active
version: 1.0.0
fhirVersion: 4.0.1
copyrightYear: 2022+
releaseLabel: fhirVersion-4.0; BCPLRVersion=1
publisher:
  name: BC Ministry of Health
  url: https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/health
jurisdiction: urn:iso:std:iso:3166#CA "Canada"

dependencies:
  hl7.fhir.ca.baseline: 1.1.7
  hl7.fhir.extensions.r5: 4.0.1 

menu:
  Overview: index.html
  FHIR Design: 
    FHIR Design and Overview: specification.html
    URL Examples: designexamples.html
  V3 Transition: transition.html
  Connected Partner: connected_partner.html
  Releases and Future Plans: future.html
  Artifacts:
    All: artifacts.html
    Capabilities: artifacts.html#1
    Operations: artifacts.html#2
    Operations Request Examples: artifacts.html#3
    Operations Response Examples: artifacts.html#4
    Bundles: artifacts.html#5
    Practitioner: artifacts.html#6
    Organization: artifacts.html#7
    Facility: artifacts.html#8    
    Healthcare Service: artifacts.html#9
    Care Team: artifacts.html#10
    Restful Response Examples: artifacts.html#11
    Extensions: artifacts.html#12
    Data Types: artifacts.html#13
    Value Sets: artifacts.html#14
  #  Code Systems: artifacts.html#13
  Technical Details: techdetails.html
  Glossary: glossary.html
  Credits: credits.html
  
pages:
  index.md:
    title: PLR Overview
  specification.md:
    title: FHIR Design and Overview
  designexamples.md:
    title: URL Examples
  transition.md:
    title: Transition from V3 Provider to FHIR
  connected_partner.md:
    title: Becoming a Connected Partner
  future.md:
    title: Releases and Future Plans
  techdetails.md:
    title: Technical Details
  glossary.md:
    title: Glossary
  credits.md:
    title: Credits

groups:
  Capabilities:
    name: Capabilities
    description: PLR Capability Statements
    resources:
      - CapabilityStatement/bc-plr-client-capability-statement
      - CapabilityStatement/bc-plr-server-capability-statement
  Operations:
    name: Operations
    description: Operation definitions
    resources:
      - OperationDefinition/bc-entity-practitioner-query
      - OperationDefinition/bc-entity-location-query
      - OperationDefinition/bc-entity-organization-query
      - OperationDefinition/bc-extended-practitioner-query
      - OperationDefinition/bc-extended-organization-query
      - OperationDefinition/bc-extended-location-query
      - OperationDefinition/bc-maintain
      - OperationDefinition/bc-distribution
      - OperationDefinition/bc-batch
  OperationsRequestExamples:
    name: Operations Request Examples
    description: Operation request examples
    resources:
      - Parameters/Example-Request-Distribution-Practitioner
      - Parameters/Example-Request-Distribution-Organization
      - Parameters/Example-Request-Add-Practitioner
      - Parameters/Example-Request-Update-Practitioner
      - Parameters/Example-Request-Update-License-Practitioner
      - Parameters/Example-Request-Add-Organization
      - Parameters/Example-Request-Add-Location
      - Parameters/Example-Request-Update-Location
  OperationsResponseExamples:
    name: Operations Response Examples
    description: Operation response examples
    resources:
      - Bundle/Example-Response-Query-Practitioner-Bundle
      - Bundle/Example-Response-Query-Organization-Bundle
      - Parameters/Example-Response-Add-Practitioner
      - Parameters/Example-Response-Update-Practitioner
      - Parameters/Example-Response-Update-Organization
      - Parameters/Example-Response-Add-Organization
      - Parameters/Example-Response-Add-Location
  Bundles:
    name: Bundles
    description: Inbound Distribution/Maintain and Batch Bundles
    resources:
      - StructureDefinition/bc-practitioner-bundle
      - StructureDefinition/bc-organization-bundle
      - StructureDefinition/bc-location-bundle
      - StructureDefinition/bc-batch-bundle
      - StructureDefinition/bc-batch-response-bundle
      - Bundle/Example-AddPractitioner-Bundle
      - Bundle/Example-DistributePractitioner-Bundle
      - Bundle/Example-AddOrganization-Bundle
      - Bundle/Example-AddLocation-Bundle
      - Bundle/Example-Batch-Bundle
  Practitioner:
    name: Practitioner
    description: Artifacts associated with Practitioners
    resources:
      - StructureDefinition/bc-practitioner
      - StructureDefinition/bc-practitioner-role
      - StructureDefinition/bc-role-relationships
  Organization:
    name: Organization
    description: Artifacts associated with Organizations
    resources:
      - StructureDefinition/bc-organization
      - StructureDefinition/bc-organization-affiliation
  Facility:
    name: Facility
    description: Artifacts associated with Facilities
    resources:
      - StructureDefinition/bc-location  
  HealthcareService:
    name: Healthcare Service
    description: Artifacts associated with Healthcare Services - no active development in PLR around this for now
    resources:
      - StructureDefinition/bc-catalogue-service  
      - StructureDefinition/bc-clinical-service 
  CareTeam:
    name: Care Team
    description: Artifacts associated with Care Teams - no active development in PLR around this for now
    resources:
      - StructureDefinition/bc-careteam
      - StructureDefinition/bc-primary-network
  RestfulQueryResponse:
    name: RESTful Query Response Examples
    description: RESTful Query Response Examples
    resources:
      - Bundle/Example-GET-Practitioner-Response
      - Bundle/Example-GET-Practitioner-Param-Response
      - Bundle/Example-GET-Organization-Response
      - Bundle/Example-GET-Location-Response
      #- Bundle/Example-GET-PractitionerRole-Response
      #- Bundle/Example-GET-PractitionerRole-byPractitioner-Response
      #- Bundle/Example-GET-OrganizationAffiliation-Response
      #- Bundle/Example-GET-OrganizationAffiliation-byOrganization-Response
  Extensions:
    name: Extensions
    description: Extensions used across all groupings
    resources:
      - StructureDefinition/bc-practitioner-deathdate-extension
      - StructureDefinition/bc-birthtime-extension
      - StructureDefinition/bc-birthplace-extension
      - StructureDefinition/bc-note-extension
      - StructureDefinition/bc-license-status-extension
      - StructureDefinition/bc-name-use-extension
      - StructureDefinition/bc-end-reason-extension
      - StructureDefinition/bc-owner-extension
      - StructureDefinition/bc-period-extension
      - StructureDefinition/bc-communication-purpose-code-extension
      - StructureDefinition/bc-practitioner-qualification-extension
      - StructureDefinition/bc-specialty-source-extension
      - StructureDefinition/bc-relationship-type-extension  
      - StructureDefinition/bc-location-relationship-type-extension  
      - StructureDefinition/bc-address-validation-status-extension
      - StructureDefinition/bc-confidentiality-extension
      - StructureDefinition/bc-practitioner-relationship-extension
      - StructureDefinition/bc-practitioner-disciplinary-action-extension
      - StructureDefinition/bc-practitioner-condition-extension
      - StructureDefinition/bc-facility-details-extension
      - StructureDefinition/bc-facility-health-service-area-extension
      - StructureDefinition/bc-facility-physical-address-extension
      - StructureDefinition/bc-operation-outcome
  Datatypes:
    name: Datatypes
    description: Artifacts associated with datatypes
    resources:
      - StructureDefinition/bc-identifier
      - StructureDefinition/bc-contactPoint
      - StructureDefinition/bc-address
      - StructureDefinition/bc-humanName
parameters:
  special-url:
    - https://terminology.hlth.gov.bc.ca/ProviderLocationRegistry/CodeSystem/bc-service-type-code-system
    - https://terminology.hlth.gov.bc.ca/ProviderLocationRegistry/ValueSet/bc-address-validation-status-value-set
    - https://terminology.hlth.gov.bc.ca/ProviderLocationRegistry/ValueSet/bc-communication-purpose-value-set
    - https://terminology.hlth.gov.bc.ca/ProviderLocationRegistry/ValueSet/bc-end-reason-value-set
    - https://terminology.hlth.gov.bc.ca/ProviderLocationRegistry/ValueSet/bc-expertise-value-set
    - https://terminology.hlth.gov.bc.ca/ProviderLocationRegistry/ValueSet/bc-language-value-set
    - https://terminology.hlth.gov.bc.ca/ProviderLocationRegistry/ValueSet/bc-license-status-class-value-set
    - https://terminology.hlth.gov.bc.ca/ProviderLocationRegistry/ValueSet/bc-license-status-reason-value-set
    - https://terminology.hlth.gov.bc.ca/ProviderLocationRegistry/ValueSet/bc-license-status-value-set
    - https://terminology.hlth.gov.bc.ca/ProviderLocationRegistry/ValueSet/bc-organization-role-value-set
    - https://terminology.hlth.gov.bc.ca/ProviderLocationRegistry/ValueSet/bc-practitioner-role-value-set
    - https://terminology.hlth.gov.bc.ca/ProviderLocationRegistry/ValueSet/bc-qualification-value-set
    - https://terminology.hlth.gov.bc.ca/ProviderLocationRegistry/ValueSet/bc-relationship-type-value-set
    