id: fhir.ca-bc.provider
canonical: http://hl7.org/fhir/ca-bc/provider
name: BCProviderRegistry
title: BC Provider Registry FHIR Implementation Guide
description: FHIR Implementation Guide for BC MOH Provider Registry
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: Build CI
publisher:
  name: BC Ministry of Health
  url: https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/health
jurisdiction: urn:iso:std:iso:3166#CA "Canada"

menu:
  Overview: index.html
  FHIR Design: specification.html
  V3 Transition: transition.html
  Connected Partner: connected_partner.html
  System Performance: system.html
  Future Plans: future.html
  Artifacts:
    Profiles: artifacts.html#1
    Extensions: artifacts.html#3
    Value Sets: artifacts.html#4
    Examples: artifacts.html#6
  Glossary: glossary.html
  Credits: credits.html
  
pages:
  index.md:
    title: PLR Overview
  specification.md:
    title: FHIR Design and Overview
  transition.md:
    title: Transition from V3 Provider to FHIR
  connected_partner.md:
    title: Becoming a Connected Partner
  system.md:
    title: Performance and Availability
  future.md:
    title: Future Plans
  glossary.md:
    title: Glossary
  credits.md:
    title: Credits

parameters:
  path-output: \docs