id: fhir.ca-bc.provider
canonical: http://hl7.org/fhir/ca-bc/provider
name: BCProviderRegistry
title: BC Provider Registry FHIR Implementation Guide
description: FHIR Implementation Guide for BC MOH Provider Registry
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: Build CI
publisher:
  name: BC Ministry of Health
  url: https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/health
jurisdiction: urn:iso:std:iso:3166#CA "Canada"

menu:
  Home: index.html
  Artifacts:
    Profiles: artifacts.html#1
    Extensions: artifacts.html#3
    Value Sets: artifacts.html#4
    Examples: artifacts.html#6
 
