id: fhir.ca-bc.provider
canonical: http://hl7.org/fhir/ca-bc/provider
name: BCProviderRegistry
title: BC Provider Registry FHIR Implementation Guide
description: FHIR Implementation Guide for BC MOH Provider Registry
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: Build CI
publisher:
  name: BC Ministry of Health
  url: https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/health
jurisdiction: urn:iso:std:iso:3166#CA "Canada"

menu:
  Overview: index.html
  FHIR Design: specification.html
  V3 Transition: transition.html
  Connected Partner: connected_partner.html
  System Performance: system.html
  Future Plans: future.html
  Artifacts:
    Operations: artifacts.html#1
    Practitioner: artifacts.html#2
    Organization: artifacts.html#3
    Facility: artifacts.html#4
    Datatypes: artifacts.html#5
    Common: artifacts.html#6
  Glossary: glossary.html
  Credits: credits.html
  
pages:
  index.md:
    title: PLR Overview
  specification.md:
    title: FHIR Design and Overview
  transition.md:
    title: Transition from V3 Provider to FHIR
  connected_partner.md:
    title: Becoming a Connected Partner
  system.md:
    title: Performance and Availability
  future.md:
    title: Future Plans
  glossary.md:
    title: Glossary
  credits.md:
    title: Credits

parameters:
  path-output: \docs
  
groups:
  Operations:
    name: Operations
    description: PLR Operations and the Bundle profiles associated with them
    resources:
      - OperationDefinition/bc-full-resource-query
      - OperationDefinition/bc-dereference-resource-query
  Practitioner:
    name: Practitioner
    description: Artifacts associated with Practitioners
    resources:
      - StructureDefinition/bc-practitioner
      - StructureDefinition/bc-practitioner-role
      - StructureDefinition/bc-practitioner-deathdate-extension
      - StructureDefinition/bc-birthtime-extension
      - StructureDefinition/bc-birthplace-extension
      - StructureDefinition/bc-practitioner-confidentiality-extension
      - StructureDefinition/bc-practitioner-relationship-extension
      - StructureDefinition/bc-practitioner-disciplinary-action-extension
      - StructureDefinition/bc-practitioner-condition-extension
      - StructureDefinition/bc-practitioner-qualification-issue-date-extension
      - Bundle/Example-AddProvider-Bundle
      - Practitioner/Example-AddProvider-Practitioner
      - Practitioner/Example-AddProvider-RelatedPractitioner
      - PractitionerRole/Example-AddProvider-PractitionerRole
      - Organization/Example-Qualification-Organization
  Organization:
    name: Organization
    description: Artifacts associated with Organizations
    resources:
      - StructureDefinition/bc-organization
      - StructureDefinition/bc-organizationaffiliation
      - Bundle/Example-AddOrganization-Bundle
      - Organization/Example-AddOrganization-Organization
      - OrganizationAffiliation/Example-AddOrganization-OrganizationAffiliation
  Facility:
    name: Facility
    description: Artifacts associated with Facilities (Locations)
    resources:
      - StructureDefinition/bc-location
      - StructureDefinition/bc-facility-details-extension
      - StructureDefinition/bc-facility-community-health-service-area-extension
      - StructureDefinition/bc-facility-mailing-address-extension
      - Location/Example-AddProvider-WorkLocation
      - Location/Example-AddOrganization-Location
  Datatypes:
    name: Datatypes
    description: Artifacts associated with datatypes
    resources:
      - StructureDefinition/bc-identifier
      - StructureDefinition/bc-contactPoint
      - StructureDefinition/bc-address
      - StructureDefinition/bc-humanName
  Common:
    name: Common
    description: Artifacts used across all groupings
    resources:
      - StructureDefinition/bc-note-extension
      - StructureDefinition/bc-license-status-extension
      - StructureDefinition/bc-name-use-extension
      - StructureDefinition/bc-end-reason-extension
      - StructureDefinition/bc-period-extension